### ISSUE TITLE
로파고 알고리즘 사용법에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by GangWoon** [jaentrouble/LoFAGO#5]
1. 로파고 알고리즘이 LoFAGO_stone.py 파일 내부에 있는걸까요?
2. dolfago.html파일 내부 계산 알고리즘이 LoFAGO 알고리즘과 동일하다면,  dolfago.html 파일의 알고리즘만 재해석해서 사용해도 괜찮을까요?(HTML 문법이 조금 더 익숙하네요...)

**Comment by jaentrouble** [comment]
> * 로파고 알고리즘이 LoFAGO_stone.py 파일 내부에 있는걸까요?
> * dolfago.html파일 내부 계산 알고리즘이 LoFAGO 알고리즘과 동일하다면,  dolfago.html 파일의 알고리즘만 재해석해서 사용해도 괜찮을까요?(HTML 문법이 조금 더 익숙하네요...)


dolfago.html은 예전에 티스토리에 있던 돌파고 웹페이지를 제가 비교용으로 긁어온 파일이라  알고리즘이 다릅니다. Html이 익숙하시면 제 깃허브보다 

https://heehoon.kim/dolpago/

여기 웹페이지 들어가셔서 소스코드 보시면 더 깨끗하게 정리된 알고리즘이 그대로 있습니다. 그걸 참고해주세요. 제 코드는 저 웹페이지 나온 이후로 손대질 않아서 지저분합니다.

**Comment by GangWoon** [comment]
친절한 가이드 감사합니다 :)

**Comment by GangWoon** [comment]
안녕하세요 엄청 오랜만에 인사드리네요.
목표는 앱스토어 출시였지만, 여러 개인적인 이유로 개인 레포에만 올리게 되었습니다.
알고리즘을 사용할 수 없었다면 시작도 못했을 거에요. 다시 한번 정말 감사합니다 :)
[저장소](https://github.com/GangWoon/LostArkAbilityStoneCalculator)
